Add wrapper to drawCharucoDiamond
opencv/opencv_contrib pull request #3011
Opened 2021-07-29 12:11 UTC by gokberkgul

`drawCharucoBoard` function can be exported since `Vec4i` is wrapped in the core

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [x] The PR is proposed to proper branch
- [x] There is reference to original bug report and related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

2021-08-30 19:10 UTC, alalek reviewed
It would be nice to have simple Python test for this case (check binding wrapper only, no need for accuracy checks - non-empty result check would be enough).

2021-09-07 13:00 UTC, andy-held requested changes

2021-09-07 13:00 UTC, andy-held commented on modules/aruco/misc/python/test/test_aruco.py
> +        aruco_dict = cv.aruco.Dictionary_get(0)
`cv2.aruco.getPredefinedDictionary(cv.aruco.DICT_4X4_50)` is more common.

2021-09-17 13:21 UTC, andy-held approved these changes

2021-09-26 17:38 UTC, alalek approved these changes

2021-09-26 17:39 UTC, merged