barcode perf tests
opencv/opencv_contrib pull request #3482
Opened 2023-04-26 12:40 UTC by MaximMilashchenko

Added four perf case for barcode. Detection and decoding time check.

2023-04-26 14:01 UTC, opencv-alalek requested changes

2023-04-26 14:16 UTC, opencv-alalek commented
Preliminary results on i7-12700K with 1/2/4/8 threads (no fixed frequency, with turbo boost enabled):

SIMD:

|Name of Test|1th|2th|4th|8th|
|---|:-:|:-:|:-:|:-:|
|decode::Perf_Barcode_multi::"4_barcodes.jpg"|2.500|2.177|2.033|1.989|
|decode::Perf_Barcode_single::"book.jpg"|0.415|0.389|0.390|0.376|
|decode::Perf_Barcode_single::"bottle_1.jpg"|0.266|0.221|0.198|0.221|
|decode::Perf_Barcode_single::"bottle_2.jpg"|0.712|0.699|0.732|0.727|
|detect::Perf_Barcode_multi::"4_barcodes.jpg"|7.527|5.939|5.486|4.888|
|detect::Perf_Barcode_single::"book.jpg"|1.679|1.660|1.670|1.685|
|detect::Perf_Barcode_single::"bottle_1.jpg"|3.243|2.687|2.447|2.326|
|detect::Perf_Barcode_single::"bottle_2.jpg"|1.974|1.985|1.975|2.045|

noSIMD / noIPP (`-DCV_DISABLE_OPTIMIZATION=ON`):

|Name of Test|1th|2th|4th|8th|
|---|:-:|:-:|:-:|:-:|
|decode::Perf_Barcode_multi::"4_barcodes.jpg"|4.615|3.477|3.162|3.060|
|decode::Perf_Barcode_single::"book.jpg"|0.650|0.584|0.586|0.579|
|decode::Perf_Barcode_single::"bottle_1.jpg"|0.536|0.406|0.341|0.295|
|decode::Perf_Barcode_single::"bottle_2.jpg"|0.975|0.881|0.872|0.871|
|detect::Perf_Barcode_multi::"4_barcodes.jpg"|9.504|7.636|6.563|6.274|
|detect::Perf_Barcode_single::"book.jpg"|2.580|2.500|2.493|2.570|
|detect::Perf_Barcode_single::"bottle_1.jpg"|4.240|3.750|3.507|3.270|
|detect::Perf_Barcode_single::"bottle_2.jpg"|2.964|2.896|2.839|2.852|

1 thread, "Generic C++" vs optimized code:

|Name of Test|generic|optimized|x-factor|
|---|:-:|:-:|:-:|
|decode::Perf_Barcode_multi::"4_barcodes.jpg"|4.615|2.500|1.85|
|decode::Perf_Barcode_single::"book.jpg"|0.650|0.415|1.57|
|decode::Perf_Barcode_single::"bottle_1.jpg"|0.536|0.266|2.02|
|decode::Perf_Barcode_single::"bottle_2.jpg"|0.975|0.712|1.37|
|detect::Perf_Barcode_multi::"4_barcodes.jpg"|9.504|7.527|1.26|
|detect::Perf_Barcode_single::"book.jpg"|2.580|1.679|1.54|
|detect::Perf_Barcode_single::"bottle_1.jpg"|4.240|3.243|1.31|
|detect::Perf_Barcode_single::"bottle_2.jpg"|2.964|1.974|1.50|

2023-04-26 16:02 UTC, opencv-alalek requested changes
Why is removed modules/barcode/test/test_barcode.cpp?

2023-04-26 16:02 UTC, opencv-alalek commented on modules/barcode/perf/perf_barcode.cpp
> +#include "perf_precomp.hpp"
License header

2023-04-26 17:54 UTC, MaximMilashchenko commented
> Why is removed modules/barcode/test/test_barcode.cpp?

it is my fault, i'll correct it

2023-04-26 18:01 UTC, MaximMilashchenko commented on modules/barcode/perf/perf_barcode.cpp
> +#include "perf_precomp.hpp"
Do you mean the comment in the header?

2023-04-28 08:06 UTC, opencv-alalek commented
@SinM9 please review this PR.

2023-05-03 12:53 UTC, SinM9 commented on modules/barcode/perf/perf_barcode.cpp
> +    cout << src.size << endl;
and here

2023-05-03 12:53 UTC, SinM9 commented on modules/barcode/perf/perf_barcode.cpp
> +    TEST_CYCLE() bardet.decode(src, corners, decoded_info, decoded_type);
TEST_CYCLE() ASSERT_TRUE(bardet.decode(src, corners, decoded_info, decoded_type)); ?

2023-05-12 05:57 UTC, opencv-alalek approved these changes
LGTM :+1:

2023-05-15 22:31 UTC, opencv-alalek requested changes
Please squash commits into one before merge.

2023-05-15 22:31 UTC, opencv-alalek commented on modules/barcode/perf/perf_precomp.hpp
> +#define __OPENCV_PERF_PRECOMP_HPP__
> `__OPENCV_PERF_PRECOMP_HPP__`

Both lines must be be the same. See GitHub Actions build error.

2023-05-17 06:02 UTC, opencv-alalek requested changes

2023-05-17 06:02 UTC, opencv-alalek commented on modules/wechat_qrcode/test/test_qrcode.cpp
> +TEST(Objdetect_QRCode_bug, issue_3478) {
Why do we have this here?

This is not your code.

2023-05-17 06:02 UTC, opencv-alalek commented on modules/barcode/test/perf_barcode
> +#include "test_precomp.hpp"
We still have this invalid file in the patch.

2023-05-24 06:54 UTC, merged