fixes #25081:Latch bug fix
opencv/opencv_contrib pull request #3646
Opened 2024-03-03 18:49 UTC by Dhanwanth1803

As mentioned by WennPaper making it `grayImage = image.clone();` will make a deep copy. It prevents the `InputArray` from being modified.

- [X] I agree to contribute to the project under Apache 2 License.
- [X] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [X] The PR is proposed to the proper branch
- [X] There is a reference to the original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

2024-03-04 07:08 UTC, dkurt commented
add a link to the issue

2024-03-04 12:56 UTC, asmorkalov approved these changes
:+1:

2024-03-04 13:56 UTC, dkurt submitted a review, later dismissed

2024-03-04 13:58 UTC, dkurt commented on modules/xfeatures2d/src/latch.cpp
> +                grayImage = image.clone();
GaussianBlur is called only for `sigma != 0.0`. So clone only then.

2024-03-04 13:59 UTC, dkurt requested changes
GaussianBlur is called only for `sigma != 0.0`. So clone only then.

2024-03-04 15:20 UTC, Dhanwanth1803 commented
> GaussianBlur is called only for `sigma != 0.0`. So clone only then.

Sir, in that case will this work? 
`case CV_8UC1:
                if (sigma_ != 0.) grayImage = image.clone();
                break;`

2024-03-04 15:22 UTC, Dhanwanth1803 commented
> GaussianBlur is called only for `sigma != 0.0`. So clone only then.

Sir, In that case will this work?
`case CV_8UC1:
                if (sigma_ != 0.) grayImage = image.clone(); 
                break; 
`

2024-03-05 04:09 UTC, dkurt commented on modules/xfeatures2d/src/latch.cpp
> +                grayImage = image.clone();
```suggestion
                grayImage = sigma_ ? image : image.clone();
```

2024-03-05 09:47 UTC, merged